"""user++

Revision ID: 102827176529
Revises: ec2f01bb13a4
Create Date: 2019-11-24 00:32:41.120432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102827176529'
down_revision = 'ec2f01bb13a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('changes', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('finished', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'finished')
    op.drop_column('user', 'changes')
    # ### end Alembic commands ###
