"""geo data addon status

Revision ID: 19a22741385b
Revises: e20fe8dddab6
Create Date: 2020-06-19 05:13:53.027617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a22741385b'
down_revision = 'e20fe8dddab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ortschaften', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ortschaften', 'status')
    # ### end Alembic commands ###
