"""VW/CopyB

Revision ID: 45db129d344f
Revises: 1c2146787eb9
Create Date: 2020-05-06 23:43:07.120229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45db129d344f'
down_revision = '1c2146787eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kopieB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_brief', sa.Integer(), nullable=True),
    sa.Column('standort', sa.String(length=200), nullable=True),
    sa.Column('signatur', sa.String(length=200), nullable=True),
    sa.Column('bemerkung', sa.String(length=500), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kopieB_id_brief'), 'kopieB', ['id_brief'], unique=False)
    op.add_column('kartei', sa.Column('ist_link', sa.Integer(), nullable=True))
    op.add_column('kartei', sa.Column('link_jahr', sa.Integer(), nullable=True))
    op.add_column('kartei', sa.Column('link_monat', sa.Integer(), nullable=True))
    op.add_column('kartei', sa.Column('link_tag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kartei', 'link_tag')
    op.drop_column('kartei', 'link_monat')
    op.drop_column('kartei', 'link_jahr')
    op.drop_column('kartei', 'ist_link')
    op.drop_index(op.f('ix_kopieB_id_brief'), table_name='kopieB')
    op.drop_table('kopieB')
    # ### end Alembic commands ###
