"""ortschaften

Revision ID: 615daca391cd
Revises: 3ebbb289aa33
Create Date: 2020-06-01 23:57:09.422643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615daca391cd'
down_revision = '3ebbb289aa33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ortschaften',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ort', sa.String(length=200), nullable=True),
    sa.Column('laenge', sa.Float(), nullable=True),
    sa.Column('breite', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ortschaften')
    # ### end Alembic commands ###
