"""comments

Revision ID: 7b1ba6aa1d97
Revises: f5f32fc81433
Create Date: 2019-12-03 02:34:45.864195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1ba6aa1d97'
down_revision = 'f5f32fc81433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_brief', sa.Integer(), nullable=True),
    sa.Column('notiz', sa.String(length=400), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notiz_id_brief'), 'notiz', ['id_brief'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notiz_id_brief'), table_name='notiz')
    op.drop_table('notiz')
    # ### end Alembic commands ###
