"""literature references

Revision ID: 94d06837579c
Revises: 49b72c74c074
Create Date: 2020-06-18 22:49:58.737941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d06837579c'
down_revision = '49b72c74c074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referenzen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literatur', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referenzen')
    # ### end Alembic commands ###
