"""empty message

Revision ID: a43e9149d215
Revises: 9ac6745c1218
Create Date: 2019-12-04 00:32:26.175121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43e9149d215'
down_revision = '9ac6745c1218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('verifiziert', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'verifiziert')
    # ### end Alembic commands ###
