"""alias user/time

Revision ID: a57e743c346e
Revises: ea879980a056
Create Date: 2020-04-07 22:39:34.541548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57e743c346e'
down_revision = 'ea879980a056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('anwender', sa.String(length=50), nullable=True))
    op.add_column('alias', sa.Column('zeit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias', 'zeit')
    op.drop_column('alias', 'anwender')
    # ### end Alembic commands ###
