"""alias is_active

Revision ID: a5c160a0c397
Revises: a57e743c346e
Create Date: 2020-04-08 00:42:27.256353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c160a0c397'
down_revision = 'a57e743c346e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alias', 'is_active')
    # ### end Alembic commands ###
