"""alias new

Revision ID: a68db4a13805
Revises: a5c160a0c397
Create Date: 2020-04-08 01:26:09.362819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68db4a13805'
down_revision = 'a5c160a0c397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=200), nullable=True),
    sa.Column('p_vorname', sa.String(length=200), nullable=True),
    sa.Column('a_name', sa.String(length=200), nullable=True),
    sa.Column('a_vorname', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alias')
    # ### end Alembic commands ###
