"""counts

Revision ID: b1ad50708abf
Revises: 102827176529
Create Date: 2019-11-25 23:04:07.303667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ad50708abf'
down_revision = '102827176529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('empfangen', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('gesendet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'gesendet')
    op.drop_column('person', 'empfangen')
    # ### end Alembic commands ###
