"""alias

Revision ID: c3515148b8ee
Revises: 29e4c0b6e620
Create Date: 2020-04-08 06:16:45.806076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3515148b8ee'
down_revision = '29e4c0b6e620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=200), nullable=True),
    sa.Column('p_vorname', sa.String(length=200), nullable=True),
    sa.Column('a_name', sa.String(length=200), nullable=True),
    sa.Column('a_vorname', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alias')
    # ### end Alembic commands ###
