"""geo data addon

Revision ID: e20fe8dddab6
Revises: 94d06837579c
Create Date: 2020-06-19 04:23:49.715087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20fe8dddab6'
down_revision = '94d06837579c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ortschaften', sa.Column('anwender', sa.String(length=50), nullable=True))
    op.add_column('ortschaften', sa.Column('zeit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ortschaften', 'zeit')
    op.drop_column('ortschaften', 'anwender')
    # ### end Alembic commands ###
