"""coords

Revision ID: ebb22a39ac11
Revises: 19a22741385b
Create Date: 2020-06-19 06:09:58.913071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb22a39ac11'
down_revision = '19a22741385b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referenzen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literatur', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('anwender', sa.String(length=50), nullable=True),
    sa.Column('zeit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ortschaften', sa.Column('anwender', sa.String(length=50), nullable=True))
    op.add_column('ortschaften', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('ortschaften', sa.Column('zeit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ortschaften', 'zeit')
    op.drop_column('ortschaften', 'status')
    op.drop_column('ortschaften', 'anwender')
    op.drop_table('referenzen')
    # ### end Alembic commands ###
