"""model reduction

Revision ID: f5f32fc81433
Revises: b1ad50708abf
Create Date: 2019-12-01 18:38:56.228234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f32fc81433'
down_revision = 'b1ad50708abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photokopie_id_brief', table_name='photokopie')
    op.drop_table('photokopie')
    op.drop_index('ix_abschrift_id_brief', table_name='abschrift')
    op.drop_table('abschrift')
    op.drop_index('ix_log_timestamp', table_name='log')
    op.drop_table('log')
    op.add_column('user', sa.Column('time', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time')
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_timestamp', 'log', ['timestamp'], unique=False)
    op.create_table('abschrift',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_brief', sa.INTEGER(), nullable=True),
    sa.Column('standort', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bull_corr', sa.INTEGER(), nullable=True),
    sa.Column('blatt', sa.INTEGER(), nullable=True),
    sa.Column('seite', sa.INTEGER(), nullable=True),
    sa.Column('anwender', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zeit', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_abschrift_id_brief', 'abschrift', ['id_brief'], unique=False)
    op.create_table('photokopie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_brief', sa.INTEGER(), nullable=True),
    sa.Column('standort', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bull_corr', sa.INTEGER(), nullable=True),
    sa.Column('blatt', sa.INTEGER(), nullable=True),
    sa.Column('seite', sa.INTEGER(), nullable=True),
    sa.Column('anwender', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zeit', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photokopie_id_brief', 'photokopie', ['id_brief'], unique=False)
    # ### end Alembic commands ###
